export const TOAST_ID_SUCCESS_UPLOAD_IMG = 'toast-success-upload-image'
export const TOAST_ID_ERROR_UPLOAD_IMG = 'toast-error-upload-image'
export const TOAST_ID_SUCCESS_RETRIEVE_IMG = 'toast-success-retrieve-image'
export const TOAST_ID_ERROR_RETRIEVE_IMG = 'toast-error-retrieve-image'
export const TOAST_ID_SUCCESS_GET_ALL_KEYS = 'toast-success-get-all-keys'
export const TOAST_ID_ERROR_GET_ALL_KEYS = 'toast-error-get-all-keys'
export const TOAST_ID_SUCCESS_DELETE_ALL_KEYS = 'toast-success-delete-all-keys'
export const TOAST_ID_ERROR_DELETE_ALL_KEYS = 'toast-error-delete-all-keys'

export const MSG_SUCCESS_UPLOAD_IMG = 'Image uploaded successfully.'
export const MSG_SUCCESS_RETRIEVE_IMG = 'Image retrieved successfully.'
export const MSG_SUCCESS_GET_ALL_KEYS = 'Keys loaded successfully.'
export const MSG_SUCCESS_DELETE_ALL_KEYS = 'Keys deleted successfully.'

export const MSG_ERROR_INCORRECT_FORMAT = 'Incorrect response format'
export const MSG_ERROR_UNKNOWN_ERR = 'Unknown Error'
export const MSG_ERROR_EMPTY_ALL_KEYS = 'No Keys Found'
