export const TOAST_ID_SUCCESS_UPLOAD_IMG = 'toast-success-upload-image'
export const TOAST_ID_ERROR_UPLOAD_IMG = 'toast-error-upload-image'
export const TOAST_ID_SUCCESS_RETRIEVE_IMG = 'toast-success-retrieve-image'
export const TOAST_ID_ERROR_RETRIEVE_IMG = 'toast-error-retrieve-image'
export const TOAST_ID_SUCCESS_GET_ALL_KEYS = 'toast-success-get-all-keys'
export const TOAST_ID_ERROR_GET_ALL_KEYS = 'toast-error-get-all-keys'
export const TOAST_ID_SUCCESS_DELETE_ALL_KEYS = 'toast-success-delete-all-keys'
export const TOAST_ID_ERROR_DELETE_ALL_KEYS = 'toast-error-delete-all-keys'

export const MODAL_ID_DELETE_ALL_KEYS = 'modal-delete-all-keys'
export const MODAL_TITLE_DELETE_ALL_KEYS = 'Delete All Keys and Images'
export const MODAL_DESCRIPTION_DELETE_ALL_KEYS = 'Are you sure you want to delete all keys and associated images? All of the data will be permanently removed. This action cannot be undone.'
export const MODAL_ID_CLEAR_CACHE = 'modal-clear-cache'
export const MODAL_TITLE_CLEAR_CACHE = 'Clear All Cache Data'
export const MODAL_DESCRIPTION_CLEAR_CACHE = 'Are you sure you want to erase the cache data? All of the data will be permanently removed and the configuration will be reset. This action cannot be undone.'
export const MODAL_ID_PUT_CONFIG = 'modal-put-config'
export const MODAL_TITLE_PUT_CONFIG = 'Confirm New Configuration'
export const MODAL_DESCRIPTION_PUT_CONFIG = 'TODO: Add description'

export const MSG_SUCCESS_UPLOAD_IMG = 'Image uploaded successfully.'
export const MSG_SUCCESS_RETRIEVE_IMG = 'Image retrieved successfully.'
export const MSG_SUCCESS_GET_ALL_KEYS = 'Keys loaded successfully.'
export const MSG_SUCCESS_DELETE_ALL_KEYS = 'Keys deleted successfully.'

export const MSG_ERROR_INCORRECT_FORMAT = 'Incorrect response format'
export const MSG_ERROR_UNKNOWN_ERR = 'Unknown Error'
export const MSG_ERROR_EMPTY_ALL_KEYS = 'No Keys Found'

export const TABLE_TITLE_ALL_KEYS = 'All Keys'
export const TABLE_DESCRIPTION_ALL_KEYS = 'keys from database + mem-cache'
export const TABLE_DELETE_TEXT_ALL_KEYS = 'Delete All'
export const TABLE_TITLE_CACHE_KEYS = 'Cache Keys'
export const TABLE_DESCRIPTION_CACHE_KEYS = 'keys from mem-cache'
export const TABLE_DELETE_TEXT_CACHE_KEYS = 'Clear Cache'
