/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
    TheConfigDivider: typeof import('./src/components/TheLayouts/TheConfigDivider.vue')['default']
    TheConfigHorizontalDivider: typeof import('./src/components/TheLayouts/TheConfigHorizontalDivider.vue')['default']
    TheConfigHR: typeof import('./src/components/TheLayouts/TheConfigHR.vue')['default']
    TheFileInput: typeof import('./src/components/TheInputs/TheFileInput.vue')['default']
    TheFooter: typeof import('./src/components/TheLayouts/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheLayouts/TheHeader.vue')['default']
    TheIconedTextInput: typeof import('./src/components/TheInputs/TheIconedTextInput.vue')['default']
    TheImagePreview: typeof import('./src/components/TheImagePreview.vue')['default']
    TheInput: typeof import('./src/components/TheInputs/TheInput.vue')['default']
    TheInputGroup: typeof import('./src/components/TheInputs/TheInputGroup.vue')['default']
    TheKeyTable: typeof import('./src/components/TheKeyTable.vue')['default']
    TheLabeledInput: typeof import('./src/components/TheInputs/TheLabeledInput.vue')['default']
    TheModal: typeof import('./src/components/TheDismissables/TheModal.vue')['default']
    ThePageContent: typeof import('./src/components/TheLayouts/ThePageContent.vue')['default']
    TheSpinner: typeof import('./src/components/TheSpinner.vue')['default']
    TheTextInput: typeof import('./src/components/TheInputs/TheTextInput.vue')['default']
    TheToast: typeof import('./src/components/TheDismissables/TheToast.vue')['default']
    TheToasts: typeof import('./src/components/TheDismissables/TheToasts.vue')['default']
    TheTooltip: typeof import('./src/components/TheDismissables/TheTooltip.vue')['default']
  }
}
